security:
    # Configuration des algorithmes de hachage des mots de passe
    password_hashers:
        App\Entity\User: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost: 15

    # Configuration des fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    # Configuration des pare-feu
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\CustomAuthenticator
            logout:
                path: app_logout
            access_denied_handler: App\Security\AccessDeniedHandler

            # Activer différentes méthodes d'authentification
            # Exemple : form_login, http_basic, etc.
            # form_login:
            #     login_path: app_login
            #     check_path: app_login

            # Exemple d'activation de l'authentification par API key
            # custom_authenticators:
            #     - App\Security\ApiKeyAuthenticator

            # Exemple d'activation de l'authentification "remember me"
            # remember_me:
            #     secret: '%kernel.secret%'
            #     lifetime: 604800 # 1 semaine en secondes
            #     path: /

            # Exemple d'activation de l'impersonation d'utilisateur
            # switch_user: true

    # Contrôle d'accès pour différentes sections du site
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: /register, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }

