controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /testroute
    controller: App\Controller\TestController::index

aide_pdf:
    path: /aide
    controller: App\Controller\AideController::showPdf