name: Pipeline-CI

on:
  push:
    branches: [ main ]  # Assurez-vous que cela correspond à votre branche principale

jobs:
  ci:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4  # Mise à jour vers la dernière version

      # Setup PHP, extensions and composer with shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Spécifiez la version de PHP que vous souhaitez utiliser
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json, mbstring, pdo

      - name: Cache Composer dependencies
        uses: actions/cache@v3  # Mise à jour vers la dernière version
        with:
          path: |
            vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress

      # Install Symfony CLI
      - name: Install Symfony CLI
        run: |
          curl -sS https://get.symfony.com/cli/installer | bash
          mv ~/.symfony/bin/symfony /usr/local/bin/symfony

      # Check vulnerabilities
      - name: Check Symfony Security
        run: symfony check:security

      # PHP CS FIXER
      - name: Run PHP-CS-Fixer
        run: |
          composer global require friendsofphp/php-cs-fixer
          ~/.composer/vendor/bin/php-cs-fixer fix --dry-run

      # PHP STAN
      - name: Run PHPStan
        run: |
          composer global require phpstan/phpstan
          composer global require phpstan/phpstan-symfony
          ~/.composer/vendor/bin/phpstan analyse src --memory-limit 1G

      - name: Lint YAML files
        run: ./bin/console lint:yaml config --parse-tags

      - name: Lint Twig templates
        run: ./bin/console lint:twig templates --env=prod

      - name: Lint Parameters and Services
        run: ./bin/console lint:container --no-debug

      - name: Lint Doctrine entities
        run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
